version: '3.5'
services:
  db:
    image: postgres
    restart: always
    hostname: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: nero
    ports:
      - "5432:5432"
    expose:
      - "5432"
volumes:
  postgres_data:
